# Generated by Django 5.0.4 on 2024-07-31 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('document', models.FileField(upload_to='documents/')),
                ('address', models.CharField(max_length=100)),
                ('email', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='signup.signup_master')),
            ],
            options={
                'unique_together': {('email',)},
            },
        ),
    ]
